language: cpp

notifications:
  email: false

install:
  - sh autogen.sh

script:   
- cmake -H. -B_build
- cmake --build _build
- _build/pack artifacts/person.json
- _build/unpack artifacts/person.json
