language: cpp

notifications:
  email: false

matrix:
  include:
  
  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-4.9
      - CMAKE_OPTIONS=-DJSON_Valgrind=ON
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-4.9', 'valgrind', 'ninja-build']
        
        
script:   
- cmake -H. -B_build
- cmake --build _build
- _build/pack artifacts/person.json
- _build/unpack artifacts/person.json
