language: cpp
sudo: false

notifications:
  email: false

matrix:
  include:

    # Linux C++14 GCC builds
    - os: linux
      compiler: gcc
      addons: &gcc7
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env: CXX_EVAL="g++-7" CC_EVAL="gcc-7" BUILD_TYPE='Release'

script:   
- cmake -H. -B_build
- cmake --build _build
- _build/pack artifacts/person.json
- _build/unpack artifacts/person.json
